# .swiftlint.yml
#
# This source file is part of the SDGCaching open source project.
# https://sdggiesbrecht.github.io/SDGCaching/macOS
#
# Copyright ©2017 Jeremy David Giesbrecht and the SDGCaching project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

excluded:
  - Packages
  - .Test Zone
disabled_rules:
  - colon
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - type_body_length
  - variable_name
